name: store_user
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: '>=3.0.5 <4.0.0'

dependencies:
    bloc: ^8.1.2
    cached_network_image: ^3.3.0
    carousel_slider: ^4.2.1
    cloud_firestore: ^4.13.5
    dio: ^5.4.0
    equatable: ^2.0.5
    firebase_auth: ^4.15.2
    firebase_core: ^2.24.2
    firebase_crashlytics: ^3.4.8
    firebase_storage: ^11.5.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.3
    flutter_facebook_auth: ^6.0.3
    flutter_map: ^6.1.0
    flutter_svg: ^2.0.9
    geolocator: ^10.1.0
    google_sign_in: ^6.1.6
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    image_picker: ^1.0.4
    intl_phone_field: ^3.2.0
    latlong2: ^0.9.0
    package_info_plus: ^5.0.1
    pinput: ^3.0.1
    smooth_page_indicator: ^1.1.0
    url_launcher: ^6.2.2
    uuid: ^4.3.2
    cherry_toast: ^1.9.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.1
    flutter_launcher_icons: ^0.13.1

flutter:
    uses-material-design: true

    assets:
        - assets/svg/
        - assets/png/
        - assets/icon/

flutter_launcher_icons:
    image_path: 'assets/icon/icon.png'
    android:
        adaptive_icon_background: '#FFA500'
        adaptive_icon_foreground: 'assets/icon/icon.png'
        min_sdk_android: 21
    ios:
# dart pub get
# dart run flutter_launcher_icons